---

- name: Create /etc/nagios/nrpe.cfg from template.
  become: true
  ansible.builtin.template:
    src: nrpe.cfg.j2
    dest: /etc/nagios/nrpe.cfg
    owner: root
    group: root
    mode: '0644'
  notify: Restart nrpe

- name: Create custom_commands.cfg in /etc/nrpe.d from template.
  become: true
  ansible.builtin.template:
    src: nrpe.d.cfg.j2
    dest: /etc/nrpe.d/custom_commands.cfg
    owner: root
    group: root
    mode: '0644'
  loop: "{{ ansible_role_nrpe_commands }}"
  notify: Restart nrpe

- name: Create scripts directory if missing.
  become: true
  ansible.builtin.file:
    path: /usr/local/scripts
    owner: root
    group: root
    mode: '0755'
    state: directory

- name: Create custom scripts from variables.
  become: true
  ansible.builtin.copy:
    content: '{{ item.data }}'
    dest: /usr/local/scripts/{{ item.name }}
    owner: root
    group: root
    mode: '0750'
  when: item.state | lower == "present"
  loop: "{{ ansible_role_nrpe_scripts }}"
  no_log: true

- name: Remove custom scripts with state set to absent.
  become: true
  ansible.builtin.file:
    path: /usr/local/scripts/{{ item.name }}
    state: '{{ item.state if item.state | lower == "absent" else "file" }}'
  loop: "{{ ansible_role_nrpe_scripts }}"
