---

- name: Install nrpe + nagios-plugins.
  become: true
  ansible.builtin.yum:
    name: "{{ ansible_role_nrpe_packages }}"
    lock_timeout: 300
    state: present
    update_cache: true

- name: Install extra nagios plugins.
  become: true
  ansible.builtin.yum:
    name: "{{ ansible_role_nrpe_extra_packages }}"
    lock_timeout: 300
    state: present
    update_cache: true
