---
- name: Include variables specific for the distribution.
  include_vars: "{{ item }}"
  with_items:
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"

- block:
    - import_tasks: install.yml
    - import_tasks: configure.yml
  when: ansible_os_family == "RedHat"
